# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='user',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='autor',
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(max_length=64, verbose_name='Nombre del proyecto'),
        ),
        migrations.DeleteModel(
            name='Administrador',
        ),
    ]
