# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 01:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='market.Administrador'),
            preserve_default=False,
        ),
    ]
