# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 03:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_proyecto_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseño',
            name='diseñador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='diseños', to='market.Diseñador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diseño',
            name='proyecto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='diseños', to='market.Proyecto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='administrador',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='market.Administrador'),
        ),
    ]
