# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 22:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20170417_0442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseño',
            name='proyecto',
        ),
        migrations.DeleteModel(
            name='Diseño',
        ),
        migrations.DeleteModel(
            name='Proyecto',
        ),
    ]
