# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20170227_0327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseñador',
            name='user',
        ),
        migrations.RemoveField(
            model_name='diseño',
            name='diseñador',
        ),
        migrations.AddField(
            model_name='diseño',
            name='apellidos',
            field=models.CharField(default='asd', max_length=64, verbose_name='Apellidos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diseño',
            name='email',
            field=models.EmailField(default='asd@a.b', max_length=254, verbose_name='Correo electrónico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diseño',
            name='nombres',
            field=models.CharField(default='asdf', max_length=64, verbose_name='Nombres'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='administrador',
            name='slug_empresa',
            field=models.CharField(editable=False, max_length=64, null=True, unique=True, verbose_name='ID único'),
        ),
        migrations.DeleteModel(
            name='Diseñador',
        ),
    ]
